name: Main

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  unit-test:
    needs: build
    name: UnitTest
    uses: ./.github/workflows/unit-test.yaml
    secrets: inherit
